#include <iostream>
#include <string>
using namespace std;

string pokemon[719] = {
  "",
  "Bulbasaur\nGrass Poison",
  "Ivysaur\nGrass Poison",
  "Venusaur\nGrass Poison",
  "Charmander\nFire",
  "Charmeleon\nFire",
  "Charizard\nFire Flying",
  "Squirtle\nWater",
  "Wartortle\nWater",
  "Blastoise\nWater",
  "Caterpie\nBug",
  "Metapod\nBug",
  "Butterfree\nBug Flying",
  "Weedle\nBug Poison",
  "Kakuna\nBug Poison",
  "Beedrill\nBug Poison",
  "Pidgey\nNormal Flying",
  "Pidgeotto\nNormal Flying",
  "Pidgeot\nNormal Flying",
  "Rattata\nNormal",
  "Raticate\nNormal",
  "Spearow\nNormal Flying",
  "Fearow\nNormal Flying",
  "Ekans\nPoison",
  "Arbok\nPoison",
  "Pikachu\nElectric",
  "Raichu\nElectric",
  "Sandshrew\nGround",
  "Sandslash\nGround",
  "Nidoran♀\nPoison",
  "Nidorina\nPoison",
  "Nidoqueen\nPoison Ground",
  "Nidoran♂\nPoison",
  "Nidorino\nPoison",
  "Nidoking\nPoison Ground",
  "Clefairy\nFairy",
  "Clefable\nFairy",
  "Vulpix\nFire",
  "Ninetales\nFire",
  "Jigglypuff\nNormal Fairy",
  "Wigglytuff\nNormal Fairy",
  "Zubat\nPoison Flying",
  "Golbat\nPoison Flying",
  "Oddish\nGrass Poison",
  "Gloom\nGrass Poison",
  "Vileplume\nGrass Poison",
  "Paras\nBug Grass",
  "Parasect\nBug Grass",
  "Venonat\nBug Poison",
  "Venomoth\nBug Poison",
  "Diglett\nGround",
  "Dugtrio\nGround",
  "Meowth\nNormal",
  "Persian\nNormal",
  "Psyduck\nWater",
  "Golduck\nWater",
  "Mankey\nFighting",
  "Primeape\nFighting",
  "Growlithe\nFire",
  "Arcanine\nFire",
  "Poliwag\nWater",
  "Poliwhirl\nWater",
  "Poliwrath\nWater Fighting",
  "Abra\nPsychic",
  "Kadabra\nPsychic",
  "Alakazam\nPsychic",
  "Machop\nFighting",
  "Machoke\nFighting",
  "Machamp\nFighting",
  "Bellsprout\nGrass Poison",
  "Weepinbell\nGrass Poison",
  "Victreebel\nGrass Poison",
  "Tentacool\nWater Poison",
  "Tentacruel\nWater Poison",
  "Geodude\nRock Ground",
  "Graveler\nRock Ground",
  "Golem\nRock Ground",
  "Ponyta\nFire",
  "Rapidash\nFire",
  "Slowpoke\nWater Psychic",
  "Slowbro\nWater Psychic",
  "Magnemite\nElectric Steel",
  "Magneton\nElectric Steel",
  "Farfetch'd\nNormal Flying",
  "Doduo\nNormal Flying",
  "Dodrio\nNormal Flying",
  "Seel\nWater",
  "Dewgong\nWater Ice",
  "Grimer\nPoison",
  "Muk\nPoison",
  "Shellder\nWater",
  "Cloyster\nWater Ice",
  "Gastly\nGhost Poison",
  "Haunter\nGhost Poison",
  "Gengar\nGhost Poison",
  "Onix\nRock Ground",
  "Drowzee\nPsychic",
  "Hypno\nPsychic",
  "Krabby\nWater",
  "Kingler\nWater",
  "Voltorb\nElectric",
  "Electrode\nElectric",
  "Exeggcute\nGrass Psychic",
  "Exeggutor\nGrass Psychic",
  "Cubone\nGround",
  "Marowak\nGround",
  "Hitmonlee\nFighting",
  "Hitmonchan\nFighting",
  "Lickitung\nNormal",
  "Koffing\nPoison",
  "Weezing\nPoison",
  "Rhyhorn\nGround Rock",
  "Rhydon\nGround Rock",
  "Chansey\nNormal",
  "Tangela\nGrass",
  "Kangaskhan\nNormal",
  "Horsea\nWater",
  "Seadra\nWater",
  "Goldeen\nWater",
  "Seaking\nWater",
  "Staryu\nWater",
  "Starmie\nWater Psychic",
  "Mr. Mime\nPsychic Fairy",
  "Scyther\nBug Flying",
  "Jynx\nIce Psychic",
  "Electabuzz\nElectric",
  "Magmar\nFire",
  "Pinsir\nBug",
  "Tauros\nNormal",
  "Magikarp\nWater",
  "Gyarados\nWater Flying",
  "Lapras\nWater Ice",
  "Ditto\nNormal",
  "Eevee\nNormal",
  "Vaporeon\nWater",
  "Jolteon\nElectric",
  "Flareon\nFire",
  "Porygon\nNormal",
  "Omanyte\nRock Water",
  "Omastar\nRock Water",
  "Kabuto\nRock Water",
  "Kabutops\nRock Water",
  "Aerodactyl\nRock Flying",
  "Snorlax\nNormal",
  "Articuno\nIce Flying",
  "Zapdos\nElectric Flying",
  "Moltres\nFire Flying",
  "Dratini\nDragon",
  "Dragonair\nDragon",
  "Dragonite\nDragon Flying",
  "Mewtwo\nPsychic",
  "Mew\nPsychic",
  "Chikorita\nGrass",
  "Bayleef\nGrass",
  "Meganium\nGrass",
  "Cyndaquil\nFire",
  "Quilava\nFire",
  "Typhlosion\nFire",
  "Totodile\nWater",
  "Croconaw\nWater",
  "Feraligatr\nWater",
  "Sentret\nNormal",
  "Furret\nNormal",
  "Hoothoot\nNormal Flying",
  "Noctowl\nNormal Flying",
  "Ledyba\nBug Flying",
  "Ledian\nBug Flying",
  "Spinarak\nBug Poison",
  "Ariados\nBug Poison",
  "Crobat\nPoison Flying",
  "Chinchou\nWater Electric",
  "Lanturn\nWater Electric",
  "Pichu\nElectric",
  "Cleffa\nFairy",
  "Igglybuff\nNormal Fairy",
  "Togepi\nFairy",
  "Togetic\nFairy Flying",
  "Natu\nPsychic Flying",
  "Xatu\nPsychic Flying",
  "Mareep\nElectric",
  "Flaaffy\nElectric",
  "Ampharos\nElectric",
  "Bellossom\nGrass",
  "Marill\nWater Fairy",
  "Azumarill\nWater Fairy",
  "Sudowoodo\nRock",
  "Politoed\nWater",
  "Hoppip\nGrass Flying",
  "Skiploom\nGrass Flying",
  "Jumpluff\nGrass Flying",
  "Aipom\nNormal",
  "Sunkern\nGrass",
  "Sunflora\nGrass",
  "Yanma\nBug Flying",
  "Wooper\nWater Ground",
  "Quagsire\nWater Ground",
  "Espeon\nPsychic",
  "Umbreon\nDark",
  "Murkrow\nDark Flying",
  "Slowking\nWater Psychic",
  "Misdreavus\nGhost",
  "Unown\nPsychic",
  "Wobbuffet\nPsychic",
  "Girafarig\nNormal Psychic",
  "Pineco\nBug",
  "Forretress\nBug Steel",
  "Dunsparce\nNormal",
  "Gligar\nGround Flying",
  "Steelix\nSteel Ground",
  "Snubbull\nFairy",
  "Granbull\nFairy",
  "Qwilfish\nWater Poison",
  "Scizor\nBug Steel",
  "Shuckle\nBug Rock",
  "Heracross\nBug Fighting",
  "Sneasel\nDark Ice",
  "Teddiursa\nNormal",
  "Ursaring\nNormal",
  "Slugma\nFire",
  "Magcargo\nFire Rock",
  "Swinub\nIce Ground",
  "Piloswine\nIce Ground",
  "Corsola\nWater Rock",
  "Remoraid\nWater",
  "Octillery\nWater",
  "Delibird\nIce Flying",
  "Mantine\nWater Flying",
  "Skarmory\nSteel Flying",
  "Houndour\nDark Fire",
  "Houndoom\nDark Fire",
  "Kingdra\nWater Dragon",
  "Phanpy\nGround",
  "Donphan\nGround",
  "Porygon2\nNormal",
  "Stantler\nNormal",
  "Smeargle\nNormal",
  "Tyrogue\nFighting",
  "Hitmontop\nFighting",
  "Smoochum\nIce Psychic",
  "Elekid\nElectric",
  "Magby\nFire",
  "Miltank\nNormal",
  "Blissey\nNormal",
  "Raikou\nElectric",
  "Entei\nFire",
  "Suicune\nWater",
  "Larvitar\nRock Ground",
  "Pupitar\nRock Ground",
  "Tyranitar\nRock Dark",
  "Lugia\nPsychic Flying",
  "Ho-oh\nFire Flying",
  "Celebi\nPsychic Grass",
  "Treecko\nGrass",
  "Grovyle\nGrass",
  "Sceptile\nGrass",
  "Torchic\nFire",
  "Combusken\nFire Fighting",
  "Blaziken\nFire Fighting",
  "Mudkip\nWater",
  "Marshtomp\nWater Ground",
  "Swampert\nWater Ground",
  "Poochyena\nDark",
  "Mightyena\nDark",
  "Zigzagoon\nNormal",
  "Linoone\nNormal",
  "Wurmple\nBug",
  "Silcoon\nBug",
  "Beautifly\nBug Flying",
  "Cascoon\nBug",
  "Dustox\nBug Poison",
  "Lotad\nWater Grass",
  "Lombre\nWater Grass",
  "Ludicolo\nWater Grass",
  "Seedot\nGrass",
  "Nuzleaf\nGrass Dark",
  "Shiftry\nGrass Dark",
  "Taillow\nNormal Flying",
  "Swellow\nNormal Flying",
  "Wingull\nWater Flying",
  "Pelipper\nWater Flying",
  "Ralts\nPsychic Fairy",
  "Kirlia\nPsychic Fairy",
  "Gardevoir\nPsychic Fairy",
  "Surskit\nBug Water",
  "Masquerain\nBug Flying",
  "Shroomish\nGrass",
  "Breloom\nGrass Fighting",
  "Slakoth\nNormal",
  "Vigoroth\nNormal",
  "Slaking\nNormal",
  "Nincada\nBug Ground",
  "Ninjask\nBug Flying",
  "Shedinja\nBug Ghost",
  "Whismur\nNormal",
  "Loudred\nNormal",
  "Exploud\nNormal",
  "Makuhita\nFighting",
  "Hariyama\nFighting",
  "Azurill\nNormal Fairy",
  "Nosepass\nRock",
  "Skitty\nNormal",
  "Delcatty\nNormal",
  "Sableye\nDark Ghost",
  "Mawile\nSteel Fairy",
  "Aron\nSteel Rock",
  "Lairon\nSteel Rock",
  "Aggron\nSteel Rock",
  "Meditite\nFighting Psychic",
  "Medicham\nFighting Psychic",
  "Electrike\nElectric",
  "Manectric\nElectric",
  "Plusle\nElectric",
  "Minun\nElectric",
  "Volbeat\nBug",
  "Illumise\nBug",
  "Roselia\nGrass Poison",
  "Gulpin\nPoison",
  "Swalot\nPoison",
  "Carvanha\nWater Dark",
  "Sharpedo\nWater Dark",
  "Wailmer\nWater",
  "Wailord\nWater",
  "Numel\nFire Ground",
  "Camerupt\nFire Ground",
  "Torkoal\nFire",
  "Spoink\nPsychic",
  "Grumpig\nPsychic",
  "Spinda\nNormal",
  "Trapinch\nGround",
  "Vibrava\nGround Dragon",
  "Flygon\nGround Dragon",
  "Cacnea\nGrass",
  "Cacturne\nGrass Dark",
  "Swablu\nNormal Flying",
  "Altaria\nDragon Flying",
  "Zangoose\nNormal",
  "Seviper\nPoison",
  "Lunatone\nRock Psychic",
  "Solrock\nRock Psychic",
  "Barboach\nWater Ground",
  "Whiscash\nWater Ground",
  "Corphish\nWater",
  "Crawdaunt\nWater Dark",
  "Baltoy\nGround Psychic",
  "Claydol\nGround Psychic",
  "Lileep\nRock Grass",
  "Cradily\nRock Grass",
  "Anorith\nRock Bug",
  "Armaldo\nRock Bug",
  "Feebas\nWater",
  "Milotic\nWater",
  "Castform\nNormal",
  "Kecleon\nNormal",
  "Shuppet\nGhost",
  "Banette\nGhost",
  "Duskull\nGhost",
  "Dusclops\nGhost",
  "Tropius\nGrass Flying",
  "Chimecho\nPsychic",
  "Absol\nDark",
  "Wynaut\nPsychic",
  "Snorunt\nIce",
  "Glalie\nIce",
  "Spheal\nIce Water",
  "Sealeo\nIce Water",
  "Walrein\nIce Water",
  "Clamperl\nWater",
  "Huntail\nWater",
  "Gorebyss\nWater",
  "Relicanth\nWater Rock",
  "Luvdisc\nWater",
  "Bagon\nDragon",
  "Shelgon\nDragon",
  "Salamence\nDragon Flying",
  "Beldum\nSteel Psychic",
  "Metang\nSteel Psychic",
  "Metagross\nSteel Psychic",
  "Regirock\nRock",
  "Regice\nIce",
  "Registeel\nSteel",
  "Latias\nDragon Psychic",
  "Latios\nDragon Psychic",
  "Kyogre\nWater",
  "Groudon\nGround",
  "Rayquaza\nDragon Flying",
  "Jirachi\nSteel Psychic",
  "Deoxys\nPsychic",
  "Turtwig\nGrass",
  "Grotle\nGrass",
  "Torterra\nGrass Ground",
  "Chimchar\nFire",
  "Monferno\nFire Fighting",
  "Infernape\nFire Fighting",
  "Piplup\nWater",
  "Prinplup\nWater",
  "Empoleon\nWater Steel",
  "Starly\nNormal Flying",
  "Staravia\nNormal Flying",
  "Staraptor\nNormal Flying",
  "Bidoof\nNormal",
  "Bibarel\nNormal Water",
  "Kricketot\nBug",
  "Kricketune\nBug",
  "Shinx\nElectric",
  "Luxio\nElectric",
  "Luxray\nElectric",
  "Budew\nGrass Poison",
  "Roserade\nGrass Poison",
  "Cranidos\nRock",
  "Rampardos\nRock",
  "Shieldon\nRock Steel",
  "Bastiodon\nRock Steel",
  "Burmy\nBug",
  "Wormadam\nBug Grass",
  "Mothim\nBug Flying",
  "Combee\nBug Flying",
  "Vespiquen\nBug Flying",
  "Pachirisu\nElectric",
  "Buizel\nWater",
  "Floatzel\nWater",
  "Cherubi\nGrass",
  "Cherrim\nGrass",
  "Shellos\nWater",
  "Gastrodon\nWater Ground",
  "Ambipom\nNormal",
  "Drifloon\nGhost Flying",
  "Drifblim\nGhost Flying",
  "Buneary\nNormal",
  "Lopunny\nNormal",
  "Mismagius\nGhost",
  "Honchkrow\nDark Flying",
  "Glameow\nNormal",
  "Purugly\nNormal",
  "Chingling\nPsychic",
  "Stunky\nPoison Dark",
  "Skuntank\nPoison Dark",
  "Bronzor\nSteel Psychic",
  "Bronzong\nSteel Psychic",
  "Bonsly\nRock",
  "Mime Jr.\nPsychic Fairy",
  "Happiny\nNormal",
  "Chatot\nNormal Flying",
  "Spiritomb\nGhost Dark",
  "Gible\nDragon Ground",
  "Gabite\nDragon Ground",
  "Garchomp\nDragon Ground",
  "Munchlax\nNormal",
  "Riolu\nFighting",
  "Lucario\nFighting Steel",
  "Hippopotas\nGround",
  "Hippowdon\nGround",
  "Skorupi\nPoison Bug",
  "Drapion\nPoison Dark",
  "Croagunk\nPoison Fighting",
  "Toxicroak\nPoison Fighting",
  "Carnivine\nGrass",
  "Finneon\nWater",
  "Lumineon\nWater",
  "Mantyke\nWater Flying",
  "Snover\nGrass Ice",
  "Abomasnow\nGrass Ice",
  "Weavile\nDark Ice",
  "Magnezone\nElectric Steel",
  "Lickilicky\nNormal",
  "Rhyperior\nGround Rock",
  "Tangrowth\nGrass",
  "Electivire\nElectric",
  "Magmortar\nFire",
  "Togekiss\nFairy Flying",
  "Yanmega\nBug Flying",
  "Leafeon\nGrass",
  "Glaceon\nIce",
  "Gliscor\nGround Flying",
  "Mamoswine\nIce Ground",
  "Porygon-Z\nNormal",
  "Gallade\nPsychic Fighting",
  "Probopass\nRock Steel",
  "Dusknoir\nGhost",
  "Froslass\nIce Ghost",
  "Rotom\nElectric Ghost",
  "Uxie\nPsychic",
  "Mesprit\nPsychic",
  "Azelf\nPsychic",
  "Dialga\nSteel Dragon",
  "Palkia\nWater Dragon",
  "Heatran\nFire Steel",
  "Regigigas\nNormal",
  "Giratina\nGhost Dragon",
  "Cresselia\nPsychic",
  "Phione\nWater",
  "Manaphy\nWater",
  "Darkrai\nDark",
  "Shaymin\nGrass",
  "Arceus\nNormal",
  "Victini\nPsychic Fire",
  "Snivy\nGrass",
  "Servine\nGrass",
  "Serperior\nGrass",
  "Tepig\nFire",
  "Pignite\nFire Fighting",
  "Emboar\nFire Fighting",
  "Oshawott\nWater",
  "Dewott\nWater",
  "Samurott\nWater",
  "Patrat\nNormal",
  "Watchog\nNormal",
  "Lillipup\nNormal",
  "Herdier\nNormal",
  "Stoutland\nNormal",
  "Purrloin\nDark",
  "Liepard\nDark",
  "Pansage\nGrass",
  "Simisage\nGrass",
  "Pansear\nFire",
  "Simisear\nFire",
  "Panpour\nWater",
  "Simipour\nWater",
  "Munna\nPsychic",
  "Musharna\nPsychic",
  "Pidove\nNormal Flying",
  "Tranquill\nNormal Flying",
  "Unfezant\nNormal Flying",
  "Blitzle\nElectric",
  "Zebstrika\nElectric",
  "Roggenrola\nRock",
  "Boldore\nRock",
  "Gigalith\nRock",
  "Woobat\nPsychic Flying",
  "Swoobat\nPsychic Flying",
  "Drilbur\nGround",
  "Excadrill\nGround Steel",
  "Audino\nNormal",
  "Timburr\nFighting",
  "Gurdurr\nFighting",
  "Conkeldurr\nFighting",
  "Tympole\nWater",
  "Palpitoad\nWater Ground",
  "Seismitoad\nWater Ground",
  "Throh\nFighting",
  "Sawk\nFighting",
  "Sewaddle\nBug Grass",
  "Swadloon\nBug Grass",
  "Leavanny\nBug Grass",
  "Venipede\nBug Poison",
  "Whirlipede\nBug Poison",
  "Scolipede\nBug Poison",
  "Cottonee\nGrass Fairy",
  "Whimsicott\nGrass Fairy",
  "Petilil\nGrass",
  "Lilligant\nGrass",
  "Basculin\nWater",
  "Sandile\nGround Dark",
  "Krokorok\nGround Dark",
  "Krookodile\nGround Dark",
  "Darumaka\nFire",
  "Darmanitan\nFire",
  "Maractus\nGrass",
  "Dwebble\nBug Rock",
  "Crustle\nBug Rock",
  "Scraggy\nDark Fighting",
  "Scrafty\nDark Fighting",
  "Sigilyph\nPsychic Flying",
  "Yamask\nGhost",
  "Cofagrigus\nGhost",
  "Tirtouga\nWater Rock",
  "Carracosta\nWater Rock",
  "Archen\nRock Flying",
  "Archeops\nRock Flying",
  "Trubbish\nPoison",
  "Garbodor\nPoison",
  "Zorua\nDark",
  "Zoroark\nDark",
  "Minccino\nNormal",
  "Cinccino\nNormal",
  "Gothita\nPsychic",
  "Gothorita\nPsychic",
  "Gothitelle\nPsychic",
  "Solosis\nPsychic",
  "Duosion\nPsychic",
  "Reuniclus\nPsychic",
  "Ducklett\nWater Flying",
  "Swanna\nWater Flying",
  "Vanillite\nIce",
  "Vanillish\nIce",
  "Vanilluxe\nIce",
  "Deerling\nNormal Grass",
  "Sawsbuck\nNormal Grass",
  "Emolga\nElectric Flying",
  "Karrablast\nBug",
  "Escavalier\nBug Steel",
  "Foongus\nGrass Poison",
  "Amoonguss\nGrass Poison",
  "Frillish\nWater Ghost",
  "Jellicent\nWater Ghost",
  "Alomomola\nWater",
  "Joltik\nBug Electric",
  "Galvantula\nBug Electric",
  "Ferroseed\nGrass Steel",
  "Ferrothorn\nGrass Steel",
  "Klink\nSteel",
  "Klang\nSteel",
  "Klinklang\nSteel",
  "Tynamo\nElectric",
  "Eelektrik\nElectric",
  "Eelektross\nElectric",
  "Elgyem\nPsychic",
  "Beheeyem\nPsychic",
  "Litwick\nGhost Fire",
  "Lampent\nGhost Fire",
  "Chandelure\nGhost Fire",
  "Axew\nDragon",
  "Fraxure\nDragon",
  "Haxorus\nDragon",
  "Cubchoo\nIce",
  "Beartic\nIce",
  "Cryogonal\nIce",
  "Shelmet\nBug",
  "Accelgor\nBug",
  "Stunfisk\nElectric Ground",
  "Mienfoo\nFighting",
  "Mienshao\nFighting",
  "Druddigon\nDragon",
  "Golett\nGround Ghost",
  "Golurk\nGround Ghost",
  "Pawniard\nDark Steel",
  "Bisharp\nDark Steel",
  "Bouffalant\nNormal",
  "Rufflet\nNormal Flying",
  "Braviary\nNormal Flying",
  "Vullaby\nDark Flying",
  "Mandibuzz\nDark Flying",
  "Heatmor\nFire",
  "Durant\nBug Steel",
  "Deino\nDark Dragon",
  "Zweilous\nDark Dragon",
  "Hydreigon\nDark Dragon",
  "Larvesta\nBug Fire",
  "Volcarona\nBug Fire",
  "Cobalion\nSteel Fighting",
  "Terrakion\nRock Fighting",
  "Virizion\nGrass Fighting",
  "Tornadus\nFlying",
  "Thundurus\nElectric Flying",
  "Reshiram\nDragon Fire",
  "Zekrom\nDragon Electric",
  "Landorus\nGround Flying",
  "Kyurem\nDragon Ice",
  "Keldeo\nWater Fighting",
  "Meloetta\nNormal Psychic",
  "Genesect\nBug Steel",
  "Chespin\nGrass",
  "Quilladin\nGrass",
  "Chesnaught\nGrass Fighting",
  "Fennekin\nFire",
  "Braixen\nFire",
  "Delphox\nFire Psychic",
  "Froakie\nWater",
  "Frogadier\nWater",
  "Greninja\nWater Dark",
  "Bunnelby\nNormal",
  "Diggersby\nNormal Ground",
  "Fletchling\nNormal Flying",
  "Fletchinder\nFire Flying",
  "Talonflame\nFire Flying",
  "Scatterbug\nBug",
  "Spewpa\nBug",
  "Vivillon\nBug Flying",
  "Litleo\nFire Normal",
  "Pyroar\nFire Normal",
  "Flabébé\nFairy",
  "Floette\nFairy",
  "Florges\nFairy",
  "Skiddo\nGrass",
  "Gogoat\nGrass",
  "Pancham\nFighting",
  "Pangoro\nFighting Dark",
  "Furfrou\nNormal",
  "Espurr\nPsychic",
  "Meowstic\nPsychic",
  "Honedge\nSteel Ghost",
  "Doublade\nSteel Ghost",
  "Aegislash\nSteel Ghost",
  "Spritzee\nFairy",
  "Aromatisse\nFairy",
  "Swirlix\nFairy",
  "Slurpuff\nFairy",
  "Inkay\nDark Psychic",
  "Malamar\nDark Psychic",
  "Binacle\nRock Water",
  "Barbaracle\nRock Water",
  "Skrelp\nPoison Water",
  "Dragalge\nPoison Dragon",
  "Clauncher\nWater",
  "Clawitzer\nWater",
  "Helioptile\nElectric Normal",
  "Heliolisk\nElectric Normal",
  "Tyrunt\nRock Dragon",
  "Tyrantrum\nRock Dragon",
  "Amaura\nRock Ice",
  "Aurorus\nRock Ice",
  "Sylveon\nFairy",
  "Hawlucha\nFighting Flying",
  "Dedenne\nElectric Fairy",
  "Carbink\nRock Fairy",
  "Goomy\nDragon",
  "Sliggoo\nDragon",
  "Goodra\nDragon",
  "Klefki\nSteel Fairy",
  "Phantump\nGhost Grass",
  "Trevenant\nGhost Grass",
  "Pumpkaboo\nGhost Grass",
  "Gourgeist\nGhost Grass",
  "Bergmite\nIce",
  "Avalugg\nIce",
  "Noibat\nFlying Dragon",
  "Noivern\nFlying Dragon",
  "Xerneas\nFairy",
  "Yveltal\nDark Flying",
  "Zygarde\nDragon Ground"
};

void solve(void) {
  int n; cin >> n;

  cout << pokemon[n];
}

int main(void) {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  solve();
  return 0;
}