name: Update README

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get install -y patchutils
          python -m pip install --upgrade pip
          pip install requests datetime

      - name: Run script to update README
        run: python scripts/update_readme.py
      
      - name: Check for changes
        run: git diff --exit-code | filterdiff -x '*:9' || exit 0

      - name: Commit and push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update README.md"
          git push
